Dj/Corey SchaferEm22/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users import views as user_views

# https://github.com/somvirs57/school_learning_management/tree/main/teaching_blog/curriculum

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    # path('register/', user_views.RegisterNow.as_view(), name='register'),
    path('register/', user_views.RegisterNowOTP.as_view(), name='register'),
    path('otp/<str:uuid>/', user_views.verifyotp, name='otp'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_reset',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
    name='password_reset'),
    path('password_reset_done',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('verification/', include('verify_email.urls')),
    path('verify/<int:pk>/<token>/', user_views.verifyemail, name= 'verifymail')
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dj/Corey SchaferEm22/blog/blogapp/urls.py
from django.urls import path
from . import views

app_name ='blogapp'

urlpatterns = [
    path('',views.BlogList.as_view(), name='home'),
    path('user/<str:username>',views.UserPostListView.as_view(), name='ussr'),
    path('post/<int:pk>',views.BlogDetailView.as_view(), name='detail'),
    path('post/ucomment/<int:pk>',views.BlogDetailView.as_view(), name='upcom'),
    path('post/dcomment/<int:pk>',views.dcomment, name='delcom'),
    path('post/new',views.BlogCreateView.as_view(), name='create'),
    path('post/<int:pk>/update',views.BlogUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete',views.BlogDeleteView.as_view(), name='delete'),
    path('about/',views.about, name= 'about'),
]

Dj/Corey SchaferEm22/blog/blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogapp:detail', kwargs={'pk': self.pk})

"""
with open('corey.json') as f:
   ...:     js = json.load(f)
for j in js:
   ...:     Post.objects.create(title=j['title'],content=j['content'], author_id=j['user_id'])
"""        

class Comment(models.Model):
    cby = models.ForeignKey(User, on_delete=models.CASCADE)
    pst = models.ForeignKey(Post,on_delete=models.CASCADE,blank=True,null=True)
    com_posted = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.TextField()

    def __str__(self):
        return f'{self.id} , {self.cby.username}'

# class Reply(models.Model):
#     comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
#     reply_body = models.TextField(max_length=500)
#     author = models.ForeignKey(User,on_delete=models.CASCADE)
#     com_posted = models.DateTimeField(default=timezone.now)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return "reply to " + str(self.comment_name)        

Dj/Corey SchaferEm22/blog/blogapp/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    content = forms.CharField(max_length=100, label="Add a comment")
    
    class Meta:
        model = Comment
        fields = ('content',)

        # widgets = {
        #     'content': Textarea(attrs={'cols': 80, 'rows': 20}),
        # }

# class ReplyForm(forms.ModelForm):
#     class Meta:
#         model = Reply
#         fields = ('reply_body',)

        # widgets = {
        #     'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        # }    

Dj/Corey SchaferEm22/blog/blogapp/views.py
from .models import Comment
from django.shortcuts import render,get_object_or_404,redirect
from blogapp.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormMixin
from .forms import CommentForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import user_passes_test
from django.core.exceptions import PermissionDenied
#  to show one form multiple time
# Create your views here.


class BlogList(LoginRequiredMixin,ListView):
    template_name = 'blogapp/home.html'
    model = Post
    context_object_name = 'r6'
    ordering = ['-date_posted']
    paginate_by = 5
    # def get_queryset(self):
    #     return Post.objects.order_by('-id')

class UserPostListView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'blogapp/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        # return Post.objects.filter(author=user).order_by('-date_posted') 
        return Post.objects.filter(author=user).order_by('-date_posted')    

class BlogDetailView(DetailView,FormMixin):
    model = Post    
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'cby':self.request.user})
        # context['comm'] = Post.objects.get(id=self.kwargs['pk']).comment_set.all().order_by('-pk')
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.cby = self.request.user
            form.instance.pst = Post.objects.get(pk = self.kwargs['pk'])
            form.save()
            return HttpResponseRedirect(reverse('blogapp:detail', args=[self.kwargs['pk']])) 
        else:
            return self.form_invalid(form)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    # if there is no success url is present it will look into get abosulte url

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form) 

    def test_func(self):
        post = self.get_object()
        #  self.get_object() this will get the post that we currently trying to update
        if self.request.user == post.author:
            return True
        return False    

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False                   

@login_required
def about(request):
    return render(request, 'blogapp/about.html')  

   
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url = '/'

    def test_func(self):
        comnt = self.get_object()
        if self.request.user == comnt.cby:
            return True
        return False 

# def checking(self):
#         comnt = get_object_or_404(Comment, id=self.pk)
#         if self.request.user == comnt.cby:
#             return True
#         return False        

# @user_passes_test(checking)
@login_required
def dcomment(request,pk):
    cmdelete = Comment.objects.get(pk=pk)   
    if request.user == cmdelete.cby:    
        cmdelete.delete()
        return HttpResponseRedirect(reverse('blogapp:detail', kwargs={'pk': cmdelete.pst.pk}))
    else:
        raise PermissionDenied


def ucomment(request,pk):
    cmdelete = Comment.objects.get(pk=pk) 
    # if request.method == 'POST':
    #     uu_form = UserUpdateForm(request.POST,instance=request.user)
    #     profile_form = ProfileUpdateForm(request.POST, request.FILES ,instance=request.user.profile)

    #     if uu_form.is_valid() and profile_form.is_valid():
    #         uu_form.save()
    #         profile_form.save()
    #         messages.success(request, f'Your account has been updated!')
    #         return redirect('profile')
    
    # else:
    #     uu_form = UserUpdateForm(instance=request.user)
    #     profile_form = ProfileUpdateForm(instance=request.user.profile)

    # context = {
    #     'uu_form': uu_form,
    #     'profile_form': profile_form
    # }

    # return render(request,'users/profile.html',context)    

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/about.html
{% extends "blogapp/base.html" %}

{% block tit %}About{% endblock  %}
{% block content %}
    {{request.role}}
    <h1>{{request.user|capfirst}}</h1>
{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blogapp/base.css' %}">
    {% block cf %}{% endblock  %}
    <title>{% block tit %}R6 Home{% endblock tit %}</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="https://www.ubisoft.com/en-gb/game/rainbow-six/siege">R6 Siege</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blogapp:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blogapp:about' %}">About</a>
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated%}
              <a class="nav-item nav-link" href="{% url 'blogapp:create' %}">New Post</a>
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% comment %} <a class="nav-item nav-link" href="{% url 'logout' %}?next={{request.path}}">Logout</a> {% endcomment %}
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href=" {% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>MADE BY</h3>
            <p class='text-muted'>Prabhat Rajput
              <ul class="list-group">
                <a class="list-group-item list-group-item-light" href="https://github.com/Prabhatrajput7">Github</a>
                <a class="list-group-item list-group-item-light" href="https://www.linkedin.com/in/prabhatrajput/">LinkedIn</a>
                {% comment %} <p class='text-muted'> Corey Schafer </p>
                <li class="list-group-item list-group-item-light">Latest Posts</li> {% endcomment %}
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/comment_confirm_delete.html
{% extends "blogapp/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete comment</legend>
                <h2>Are you sure you want to delete the comment "{{ object.content }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blogapp:detail' object.pst.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/home.html
{% extends "blogapp/base.html" %}

{% block tit %}Home{% endblock  %}
{% block content %}
    {% for post in r6 %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href=" {% url 'blogapp:ussr' post.author %} ">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href=" {% url 'blogapp:detail' post.id%} ">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>

    {% endfor %}

    {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} 
       {% comment %}1[-2,4] 2[-2,4] 3[-2,4] 4[-2,4]  {% endcomment %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}

{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/post_confirm_delete.html
{% extends "blogapp/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blogapp:detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/post_detail.html
{% extends "blogapp/base.html" %}
{% load crispy_forms_tags %}
{% block tit %}{{object.author}}{% endblock  %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == request.user%}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blogapp:update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blogapp:delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
  
  {% if comm %}
  <h3>Comments</h3>
  {% for c in  comm%}
  <article class="media content-section">
    {% if c.cby == request.user%}
    <div>
      {{c.content}} by {{c.cby}} <br>
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blogapp:update' c.id %}">Update</a>
      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blogapp:delcom' c.id %}">Delete</a>
    </div>
    {% else %}
    {{c.content}} by {{c.cby}} <br>
    {% endif %}
  </article>
  {% endfor %}
  {% else %}
  {% endif %}

    <form method="POST">
        {% csrf_token %}
            {{ form|crispy }}
            {{ reply|crispy }}
            <button class="btn btn-outline-info" type="submit">Post</button>
    </form>
{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/post_form.html
{% extends "blogapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

Dj/Corey SchaferEm22/blog/blogapp/templates/blogapp/user_posts.html
{% extends "blogapp/base.html" %}

{% block tit %}  {{view.kwargs.username}}{% endblock  %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href=" {% url 'blogapp:ussr' post.author %} ">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'blogapp:detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}